#!/bin/bash
cd `dirname $0`

echo "---------------------------------------------------------------"
echo "fetch and update started at" $(date)

bundle exec rake fetch:people
bundle exec rake fetch:organizations
bundle exec rake fetch:articles
bundle exec rake update:counter

echo "fetch and update finished at" $(date)
cd -
